### ISSUE TITLE
Collections Don't Work

### ISSUE THREAD

**Issue by vw3i** [supertiger1234/nertivia.js#18]
Well I've obviously tried:

```js
const Nertivia = require('nertivia.js');

bot.commands = new Nertivia.Collection();
bot.aliases = new Nertivia.Collection();
bot.usages = new Nertivia.Collection();
```
But then I get this:
![image](https://user-images.githubusercontent.com/69738839/91464390-6304d200-e841-11ea-8442-7403f5c616b3.png)

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/nertivia.js/commit/d40680af50d86ff045b3514fcf9732dc788a8278
Fixed, thanks
