### ISSUE TITLE
[FEATURE] Way to look for a member mention

### ISSUE THREAD

**Issue by CyberL1** [supertiger1234/nertivia.js#6]
`message.mentions.[users/bots/members][array]`, so for example `message.mentions.members[0]` will get the first mention and `1` will get second mention etc...

**Comment by CyberL1** [comment]
members = users + bots ofc

**Comment by supertiger1234** [comment]
you can now use `message.mentions` to get mentions https://github.com/supertiger1234/nertivia.js/commit/0cfbb25a8714cec4385e28df1f1abe560453c5ff
Thanks!
